### ISSUE TITLE
Dataset.p

### ISSUE THREAD

**Issue by indraunity99** [ornberg/Sign-Language-Recognition#1]
Can you tell me where can i find dataset ?
I think, you can use exception to handle error ? 

IOError: [Errno 2] No such file or directory: 'dataset.p'

**Comment by ornberg** [comment]
You create your own with `Builder.py`, but I see that file handling was sloppy; it didn't create an empty pickle file if none existed. Should be working now.

Also, I should definitely write some error handling. Thanks

**Comment by indraunity99** [comment]
Hi Onrberg, thanks for respone, i will try your code. 
your code make me so curious
