### ISSUE TITLE
Explain Dataset.p

### ISSUE THREAD

**Issue by indraunity99** [ornberg/Sign-Language-Recognition#3]
Hi, Ornberg, finally i can running your program.
I need know, what you store in dataset.p
can you explain me ? 

`(lp0
(iutils
Sign
p1
(dp2
S'type'
p3
S'Fixed'
p4
sS'samples'
p5
(lp6
(lp7
F40.735483487447105
aF-9.353773752848307
aF-17.552099863688152
aF28.756785074869793
aF36.87839380900065
aF-89.33992258707683
aF46.88424332936605
aF-40.34800720214844
aF-5.125576019287109
aF31.61873213450114
aF-46.949501037597656
aF-0.27042357126871747
aF16.360365470250446
aF-43.4810848236084
aF-5.719992001851399
aF18.060137755216655
aF174.67973729963674
aasS'value'
p8
S'one'
p9
sba.`

**Comment by ornberg** [comment]
Hi again @indraunity99! I'm sorry for not getting back to you, I went offline for a week and then completely forgot about it.

Good to hear you're able to run it now. What did you do differently? I was only able to reproduce the same error by adding an empty list as a sample in a class on purpose, but I fail to see how that would happen in practice. I'll add some more error handling in a new commit soon.

The `dataset.p` consists of
```
A list of objects of the Signs class, where each Sign consists of:
  1. A value (name)
  2. Its Sign type (either 'Fixed' or 'Gesture')
  3. A list of lists (samples), which each holds either 17 or 200 floating point numbers,
  depending on the Sign type
```

Also, it's stored as a pickle file, so just opening it in a text editor will result in the funky format you posted.

**Comment by indraunity99** [comment]
No problem dude. I still find how to running your program :)

I dont understand, if i'm running in windows, your program is not working. 
But if i run on mac intepreter it's doing fine, although sometimes an error like this

` if result[0][2] < 0.85: #Novelty detection based on results euclidean distance
IndexError: list index out of range`

ah, I also declare pickle  (import pickle ) in utils.py and program can detect my gesture. 
i'm still waiting your commit 👍 

THANK'S

**Comment by ornberg** [comment]
So on Windows it's not working at all? What kind of error messages do you get when you try to run it?

Sounds like we're back to the same problem you mentioned earlier [here](https://github.com/ornberg/Sign-Language-Recognition/issues/2#issuecomment-277229298).
The reasons it happens 'sometimes', is because I suspect it tries to classify it as a `Gesture` when there are non of that type in `dataset.p`. The code update I just did should resolve that, as it now only trains a classifier for either `Fixed` or `Gesture` if there actually are any signs.

**Comment by indraunity99** [comment]
Ok ornberg, 

in windows, i just get message 

`File "C:/Users/Master/Desktop/Development/Source/Sample/SignLanguageApp/NBClassifier.py", line 63, in probabilities
    distances.append(self.euclidian(vector,self.classes[_class][0]) / self.classes[_class][3])
ZeroDivisionError: float division by zero`

when i run interpreter. 
now i want to understanding your code 👍

**Comment by indraunity99** [comment]
hi this is error in you new commit ornberg 

`line 108, in validateVector for feature in keyframe:
TypeError: 'float' object is not iterable`

This happened in utils.py

**Comment by ornberg** [comment]
Sorry about that, a few things are tricky to catch when I don't have a Leap Sensor anymore. I've updated `utils.py` now.

As for the `ZeroDivisionError` on Windows environments; I'll test this as soon as I can (I am unable to run a VM at the moment).
A question first tho: Are you running Windows 10 and still Python 2.7?

**Comment by indraunity99** [comment]
It's okay, Take it easy dude, In fact do not bother yourself

Yup i'm running in windows 10 Phyton 2.7. 
But i know what the problem now. 
If i record fixed sign, program is running fine (intepreter)
But if i record as gesture, intepreter always say error 

`line 31, in <lambda>
    base = sum(map(lambda x : math.log(2 * math.pi * x), variance)) * (-0.5)
ValueError: math domain error`

at NBClassifier. (this problem in old code)

In new code i can't record gesture type. 
get error like this 

`line 201, in stopRecording
    self.currentSign.samples.append()
TypeError: append() takes exactly one argument (0 given)`

at Builder.py


I dont understand, how the builder work for  record gesture ? 
can u explain step by step ?

**Comment by ornberg** [comment]
Ran a quick test in W10 VM, but came up short; I can't seem to reproduce that particular `ZeroDivisionError`. As I mentioned earlier, the only viable cause I could think of that would make that happen was if a sample would be an empty list. There might be a case where polling data from the Leap sensor results in no values at all (not just the number zero), but I don't know for sure.

Hm. Looks like we're back to the issue of having several values being zero across features, [just like before](https://github.com/ornberg/Sign-Language-Recognition/issues/2#issuecomment-276954408). I have added a few lines to catch this error when recording samples in `Builder.py` and when importing the `dataset.p` in `Interpreter.py`.
If you run [this test script](https://drive.google.com/open?id=0Bz9r1bWx5kEGTmpoa1ZCVmY1R2M) in the same folder you'll see what I mean.
I scanned through a bunch of older datasets I had laying around, back from when I still had a Leap sensor; None of the datasets had any missing values. So I am afraid this might be something related to how the Leap SDK behaves on some computers or with some particular sensors.

The third error was just a missing variable name; again, coding without a sensor makes it trickier to rule out those simple "typos". It should be fine now.

As for the recording of gestures; `Builder.py` copies a frame roughly every 0.01 seconds when you hold down the `Record` button. When you release the button, and 10 or more frames have been recorded (aka more than ca. 0.1 seconds) the values are extracted (finger xyz, palm pitch and so on). Then they are averaged down to 10 keyframes and stored in `dataset.p`. More or less. The concept is described in [the accompanying PDF](https://github.com/ornberg/Sign-Language-Recognition/blob/master/Final%20Year%20Project%20Report.pdf), although it's a little long winded.

**Comment by indraunity99** [comment]
Thank's Onberg, i will try your code now. 
Actually i want to compare your method with SVM method.

if I want to make the SVM method with the your data recorder, does this work? I need your advice to make the SVM method.

**Comment by ornberg** [comment]
The Naïve Bayes classifier I implemented isn't doing anything more than for instance [scikits Gaussian NB classifier](http://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.GaussianNB.html#sklearn.naive_bayes.GaussianNB). And sure, you can hook up any type classifier you like, like a [SVM](http://scikit-learn.org/stable/modules/svm.html) as you suggest. However, you'll need to do a few modifications.
`Interpreter.py` sorts samples into a list of tuples like `(label, sample)`, where as scikit classifiers take a list of two lists like `[[sample, sample, ...], [label, label, ...]]`, so you'll have to change that.
Additionally, you'll have to change novelty detection to work with the library of your choosing, which would be a good thing; there are far more [sophisticated methods out there](http://scikit-learn.org/stable/modules/outlier_detection.html) than the simple average Euclidean distance method I used. Alternatively you could drop outlier detection all together if you don't need it.

**Comment by indraunity99** [comment]
Ornberg, big thank's for you for helping me.
Meybe next time i will ask you again. 
sorry if i have many questions and troubling you.
can i have your email ?
